version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Backend Docker image...
      - docker build -t ilan25/devbank-backend:latest .
      - docker tag ilan25/devbank-backend:latest ilan25/devbank-backend:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo Pushing the Docker images to Docker Hub...
      - docker push ilan25/devbank-backend:latest
      - docker push ilan25/devbank-backend:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Writing imagedefinitions.json for ECS...
      - printf '[{"name":"backend-container","imageUri":"ilan25/devbank-backend:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
